# Generated by Django 5.2.4 on 2025-07-20 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionbox',
            name='buyer',
            field=models.ForeignKey(blank=True, help_text="User of type 'customer'", limit_choices_to={'user_type': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionbox',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text="User of type 'vendor'", limit_choices_to={'user_type': 'vendor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleditem',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_items', to='subscription.subscriptionbox'),
        ),
    ]
