# Generated by Django 5.2.4 on 2025-07-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(default='M-Pesa', help_text='Payment method', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('merchant_request_id', models.CharField(max_length=100, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, help_text='Unique Checkout Request ID from M-Pesa', max_length=100, null=True, unique=True)),
                ('result_code', models.CharField(blank=True, help_text='M-Pesa Result Code', max_length=10, null=True)),
                ('result_desc', models.TextField(blank=True, help_text='M-Pesa Result Description', null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa Transaction Receipt Number', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for payment', max_length=15, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, help_text='Date and time of the transaction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the payment record was last updated')),
                ('order', models.ForeignKey(default=1, help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'indexes': [models.Index(fields=['merchant_request_id'], name='payment_pay_merchan_5de281_idx'), models.Index(fields=['checkout_request_id'], name='payment_pay_checkou_e2f706_idx'), models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'), models.Index(fields=['order_id'], name='payment_pay_order_i_211f02_idx')],
            },
        ),
    ]
